### ISSUE TITLE
Issue for Blue Reflection Second Light's Mainfont

### ISSUE THREAD

**Issue by snavellib** [VitaSmith/gust_tools#90] opened 2024-01-20 18:04 UTC
I'm not good at English, so I borrowed the help of a translator. Please understand if there is something awkward about the sentence.

Blue Reflection Second Light has five font files.

externalchars_hd1080_0.g1t
**mainfont00_hd1080_0.g1t
mainfont00_hd1080_1.g1t
mainfont00_hd1080_2.g1t**
subfont_hd1080.g1t

Among them, externalchars_hd1080_0.g1t and subfont_hd1080.g1t can be edited normally, but mainfont00_hd1080_0~2 look broken.

![000](https://github.com/VitaSmith/gust_tools/assets/90432635/bcc0da70-b8dc-4997-9208-aa9a3cf7309f)

There is no problem unpack and repack files through gust_g1t.exe (probably due to #50 issue and 1.46 update)

Can I get some help regarding mainfonts?

Use this files if you need it.
[Font.7z](https://drive.google.com/file/d/1N5IXgQIHQRJV7T--xO8BPI8J-tXgFWMU/view?usp=sharing)

**Comment by VitaSmith** [comment] 2024-01-20 19:00
Duplicate of #80.

**Closed by VitaSmith** 2024-01-20 19:00 UTC

**Comment by snavellib** [comment] 2024-01-21 01:06
Sadly, I have already confirmed that before.

I'm not good at handling CT2, I want '.dds file' that I can read and write in Photoshop.
Is there a way to get it using CT2? or Do you have any plans to update gust_g1t to support it?
