### ISSUE TITLE
Gust_Enc decodes files fine, but won't encode

### ISSUE THREAD

**Issue by vedaxi52** [VitaSmith/gust_tools#21] opened 2020-08-13 17:34 UTC
Running Gust_enc.exe on Atelier Ryza, I have the JSON file set to A21 for the seed, yet it won't encode files properly, it will only decode them. When I attempt to encode a file, it spits out a file of the same size as the unencoded XML, this file it spits out also can't be decoded and throws the issue "Glaze decompression buffer is too small"

**Comment by VitaSmith** [comment] 2020-08-13 20:53
Thanks for the report.

It's possible I introduced a regression with the latest version of the tools, as I had to modify `gust_enc` extensively to add support for Fairy Tail.

While I investigate the issue, you may want to use the [1.19 version of `gust_enc`](https://github.com/VitaSmith/gust_tools/releases/tag/v1.19) as you may find that it works better...

**Comment by vedaxi52** [comment] 2020-08-13 22:51
Tried using 1.19, I have the same issue. It's possible I'm using it wrong, but it seems pretty straightforward. Drag the XML onto the executable after changing the SeedID to A21

**Comment by vedaxi52** [comment] 2020-08-13 23:05
Using 1.19 resolved the issue, though the file size is larger than the base encoded one. Thank you!

**Comment by VitaSmith** [comment] 2020-08-14 01:43
The "recompressed" file size being larger than the uncompressed one is [absolutely normal](https://github.com/VitaSmith/gust_tools/blob/c266042f952f69027e3720b6c9dd73cd8838f12f/gust_enc.c#L424-L434).

There's very little point in adding actual compression for modding, and I just don't have time to spare to reengineer a whole compression algorithm (since we don't have a source for that, even from the disassembly) just to be on par with what Gust does, as it doesn't affect our ability to create files that the engine will accept. So we just shove the whole uncompressed file into a dictionary and then add a bunch of "copy from dictionary" commands for our decompression as a very efficient shortcut

Now, if someone can point me to a public source for the compression algorithm that Gust use, I'll be more than happy to add it. But until then, files "compressed" by `gust_enc` will always be larger than the uncompressed version.

Outside of this, I'll fix the regression from 1.19 when I get a chance.

**Comment by VitaSmith** [comment] 2020-08-14 10:53
This should be fixed in the latest release. Thanks again for reporting the issue!

**Closed** 2020-08-14 10:53 UTC
