### ISSUE TITLE
Atelier Arland DX .g1t files have the wrong colors

### ISSUE THREAD

**Issue by Zardas81** [VitaSmith/gust_tools#12] opened 2020-04-27 05:43 UTC
The .g1t files found in the remastered PC version of the Arland games (A11V-A13V) come out like this when converted:

![000](https://user-images.githubusercontent.com/30408291/80337565-7e8faa00-885a-11ea-9f49-691ff4ccbbe8.jpg)

Original file: [A11V_PLUS_11.zip](https://github.com/VitaSmith/gust_tools/files/4537691/A11V_PLUS_11.zip)

**Comment by Joschuka** [comment] 2020-04-27 17:26
Seems like an offset issue, the format is BC7 (code 5F) which is supposed to be supported.
![A11V_PLUS_11](https://user-images.githubusercontent.com/43338144/80401660-ff7f8d80-88bc-11ea-8fe1-502749f533e2.PNG)

**Comment by Zardas81** [comment] 2020-04-29 05:49
Yeah, thought so. Is there anything I can do to fix it on my end, or does it need a program update?

**Comment by Joschuka** [comment] 2020-04-30 13:28
It needs a program update unless you're familiar with the G1T format.
In the meantime you can use the texture cooker to extract them manually or my Noesis plugin https://github.com/Joschuka/fmt_g1m

**Comment by VitaSmith** [comment] 2020-05-03 00:53
Should be fixed now.

The problem is that we followed what Steven's Gas Machine/Xentax does (which says that texture type `0x5F` is supposed to "work perfectly") for the `DDS_HEADER_DXT10` header section, and in `x_dds.cpp` &rarr; `CreateBC7Header()` they set `arraySize` to `0` which is completely wrong.

Per [Microsoft's doc]((https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-header-dxt10)):

> For a 3D texture, you must set this number to 1.

Having `0` instead of `1` there made the texture invalid.

**Closed** 2020-05-03 00:53 UTC
