### ISSUE TITLE
Blue Reflection g1t PSV

### ISSUE THREAD

**Issue by kevin168** [VitaSmith/gust_tools#23] opened 2020-09-03 17:54 UTC
Hello, i've tried to unpack g1t files from PS Vita Blue Reflection,
unpack/repacked file produced swizzle *.dds.

i could unpack correctly using noesis + fmt_g1m plugin, but there is no option to repack it.

will be great if this could be supported, 

[PC00.zip](https://github.com/VitaSmith/gust_tools/files/5170340/PC00.zip)

**Comment by kevin168** [comment] 2020-09-09 05:46
gust_g1t actually working when unpack repacking, file can be loaded into psv.
Tried to recreate *dds manually, because gust_g1t unpacked swizzled image.

Here is one problem that i still can't fixed.
On the original *.dds file format is DXT1 with 2 mipmap layers.
There is different swizzled image's within those 2 layers.

Can't figure it out how to swizzled 2nd mip layer correctly.

If anyone willing to look up into this issue, i'll be glad to provide more details.

Thank's

**Comment by VitaSmith** [comment] 2020-09-09 12:16
Yes, this is a duplicate of #6. `gust_g1t` explicitly tells you, on its console output that, while it can try to extract them, texture types `0x10` and `0x12` are not officially supported...

To properly support these, I'd have to add proper generic swizzling, and possibly rewrite other parts of the code, but, since I'm plenty busy on other things, and this project is not a high priority for me, it'll probably be months or years  before I do that... if I ever do that.

I'll accept a patch though, if someone is willing to churn through something like [this article](https://fgiesen.wordpress.com/2011/01/17/texture-tiling-and-swizzling/) and add the required swizzing for `0x10` and `0x12`.

**Comment by kevin168** [comment] 2020-09-11 17:56
Hello,
Sorry that i didn't have enough capability to commit a patch for now. 
This was my first time playing around in game modding scene.
I read the article several times.

As english isn't my native language, i need some more time to understand it correctly.

I also found an interesting code, don't know if this could be useful, please take a look when you've some free time.

https://github.com/amg98/Atlas/blob/master/tools/vita-swizzler/main.cpp

Thank's

**Comment by VitaSmith** [comment] 2021-09-04 23:39
Support for multi mipmap PSV textures should work now.

**Closed** 2021-09-04 23:40 UTC
